blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "问道编程"
__date__ = "2018-07-04 14:45"

from django.urls import path

from .views import *

urlpatterns = [
    path('index/', Index.as_view(), name='index'),
    path('about/', About.as_view(), name='about'),
    path('archive/', Archive.as_view(), name='archive'),
    path('link/', Link.as_view(), name='link'),
    path('message', Message.as_view(), name='message'),
    path('article/<int:pk>/', Articles.as_view(), name='article'),
    path('get_comment/', GetComment, name='get_comment'),
    path('detail/<int:pk>/', Detail.as_view(), name='detail'),
    path('search/', Search.as_view(), name='search'),
    path('tag/<int:id>/', Tagcloud.as_view(), name='tag'),

]

myblog/urls.py
from django.conf import settings
from django.views.static import serve  # 处理静态文件
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
import xadmin

from blog.views import *

urlpatterns = [
    path('admin/', xadmin.site.urls),

    path('',Index.as_view(),name='index'),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),

]

if settings.DEBUG:
    #  配置静态文件访问处理
    urlpatterns.append(url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))
    urlpatterns.append(url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}))


# 全局页面配置
handler403 = 'blog.views.page_not_look'
handler404 = 'blog.views.page_not_found'
handler500 = 'blog.views.page_error'

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/about.html
{% extends "base.html" %}

{% block title %}
    <title>AboutMe - 烂笔头</title>
{% endblock %}

{% block content %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">页面建设中。。。。</section>

{% endblock %}

templates/archive.html
{% extends "base.html" %}
{% load custom_filter %}

{% block title %}
    <title>博客归档 - 烂笔头</title>
{% endblock %}

{% block css %}
    <link href="/static/archives/style.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
    <section class="mysection main" style="animation: fuxiasuo 0.8s;">
        <ul class="timeline">
            {% for article in article_list %}
                <li class="event">
                    <input type="radio" name="tl-group" {% if forloop.counter0 == 0 %} checked {% endif %}/>
                    <label></label>
                    <div class="thumb"><span>{{ article.edit_time }}</span></div>
                    <div class="content-perspective">
                        <div class="content">
                            <div class="content-inner">
                                <h3><a href="{% url "blog:detail" article.id%}">{{ article.title }}</a></h3>
                                <p>{{ article.digest }}</p>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

templates/articles.html
{% extends "base.html" %}
{% load custom_filter %}

{% block title %}
    <title>博客列表 - 烂笔头</title>
{% endblock %}

{% block content %}
    {% paginate article_list 8 %}
    {% if article_list %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:article" 0 %}"><i class="el-th-list"></i>{% if category %}列表{% else %} 全部 {% endif %} &nbsp;&nbsp;> &nbsp;&nbsp;</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共有文章:<a class="orange-text"> {{ count }} </a>篇</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.read_nums > 500 %}id="tuijian"{% elif article.read_nums > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ MEDIA_URL }}{{ article.image }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.edit_time }} 发表 "><i class="el-time"></i> {{ article.edit_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.conment_nums }} 条评论"><i class="el-comment"></i>{{ article.conment_nums }}</a>
                            </li>
                            <li><a title="已有 {{ article.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ article.read_nums }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "blog:article" article.category.id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category.name }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>
                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>
    {% else %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>
    {% endif %}

{% endblock %}

templates/blogroll.html
<!--友情链接-->
<div class="side-link animation-div">
    <h4 class="index-title"><i class="el-paper-clip"></i>友情链接
        <small>Friend Links</small>
        <a href="mailto:online_learn_edu@sina.com?subject=博客友链互换&body=博客名称:<br> 博客描述:<br>博客地址:"><i class="el el-plus"></i>申请</a></h4>
    <ul>
        <li><a href="https://www.zaoshu.io/" target="_blank" title="智能云爬虫">造数</a></li>
        <li><a href="http://brucedone.com/" target="_blank" title="大鱼的鱼塘 - 一个总会有收获的地方">大鱼的鱼塘</a></li>
        <li><a href="http://www.songluyi.com/" target="_blank" title="">灯塔水母</a></li>
        <li><a href="http://blog.topspeedsnail.com/" target="_blank" title="本博客专注于技术，Linux，编程，Python，C，Ubuntu、开源软件、Github等">斗大的熊猫</a></li>
        <li><a href="https://www.urlteam.org/" target="_blank" title="本博客专注于技术，Linux，编程，Python，C，Ubuntu、开源软件、Github等">URL-team</a></li>
    </ul>
</div>

templates/header.html
<header class="myheader">
    <div class="top">
        <!--头像左边部分-->
        <div class="top-left">
            <div class="logo"><a href="/"><img src="/static/images/h.gif"/></a></div>
{#                <div class="logo"><a href="#"><img src="/static/images/logo.png"/></a></div>#}

            <!--滚动消息-->
            <div class="web-xiaoxi">
                <i class="el-speaker"></i>
                <ul class="mulitline">
                    <li>正在最后的优化</li>
                    <li>完成后将放出模板</li>
                    <li>完美自适应手机</li>
                </ul>
            </div>
            <!--END 消息 -->

            <!--手机菜单按钮-->
            <div class="mobile-nav"><i class="el-lines"></i><i class="el-remove"></i></div>
        </div>
        <!--电脑导航开始-->
        <nav class="mynav">
            <ul class="orange-text">
                <li class=""><a href="{% url "blog:index" %}">首页</a></li>
                <li><a href="{% url "blog:about" %}">关于</a></li>
                <li><a href="{% url "blog:article" 0 %}">博客</a></li>
                <li class='drop'>
                    <a href="JavaScript:;">分类<i class='el-chevron-down'></i></a>
                    <div class="drop-nav orange-text ">
                        <ul>
                            {% for category in category_list %}
                                <li><a href="{% url "blog:article" category.id %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li><a href="{% url "blog:archive" %}">归档</a></li>
                <li><a href="{% url "blog:link" %}">链接</a></li>
                <li><a href="{% url "blog:message" %}">留言</a></li>
            </ul>
        </nav>

        <!--这里是手机导航-->
        <div class="mob-menu">
            <!--手机顶部搜索-->
            <div class="search ">
                <form action="{% url "blog:search" %}" method="get">
                    <div class="search-index">
                        <input name="name" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                               onblur="this.placeholder='请输入关键字'"/>
                        <i class="el-search"><input value=" " type="submit"/></i>
                    </div>
                </form>
            </div>
            <!--手机下拉菜单-->
            <ul>
                <li><a href="{% url "blog:index" %}">首页</a></li>
                <li><a href="{% url "blog:about" %}">关于</a></li>
                <li><a href="{% url "blog:article" pk=0 %}">博客</a></li>
                <li class='mob-drop'>
                    <a href="javascrip:;">分类</a>
                    <ul class="mob-dropmenu">
                        {% for category in category_list %}
                            <li><a href="{% url "blog:article" category.id %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url "blog:archive" %}">归档</a></li>
                <li><a href="{% url "blog:link" %}">链接</a></li>
                <li><a href="{% url "blog:message" %}">留言</a></li>
            </ul>
        </div>
    </div>
    <!--换肤--->
    <script src="/static/js/skin.js"></script>
    <div class="select-skin">
        <div class="skin-btn">
            <a href="javascript:void(0);" class="skin-btn-open">换<br>肤</a>
        </div>

        <div class="skin-content">
            <h1>选择风格<span class="skin-close">关闭</span></h1>
            <div class="skin-content-list">
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingxin'); return false;" class="btn1">清新</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('jianyue'); return false;" class="btn2">简约</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingshuang'); return false;"
                                          class="btn3">清爽</a></div>
            </div>
        </div>
    </div>
</header>

templates/link.html
{% extends "base.html" %}

{% block title %}
    <title>链接 - 烂笔头 </title>
{% endblock %}

{% block content %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">页面建设中。。。。</section>

{% endblock %}

templates/right.html
<aside class="myaside">
    <!--关注我-->
    <div class="focus-me bg-color animation-div">
        <h4 class="index-title"><i class="el-heart"></i>关注我
            <small>Focus Me</small>
        </h4>
        <div class="xiangguan">

            <div><a class="benbo" href="https://github.com/myminwang/myblog.git" target="_blank"><i
                    class="el-download-alt"></i></a><span>博客源码</span></div>
            <div><a class="taobao"
                    href="http://www.mylanbitou.top"
                    target="_blank"><i class="el-blogger"></i></a><span>博客地址</span></div>
            <div><a class="side-fx"><i class="el-share-alt"></i></a><span>分享本博</span></div>
            <div><a class="mail-btn" href="javascript:;"><i class="el-envelope"></i></a><span>订阅我</span></div>
        </div>

        <div class="mail-dy">
            <form action="#">
                <input type="hidden" name="t" value="qf_booked_feedback"/>
                <input type="hidden" name="id" value="b2b151b4bc010575c083e18e227ae907aac82bc47e84d3e0"/>
                <span>订阅</span>
                <input name="to" type="text" placeholder="输入邮箱点击订阅吧" onfocus="this.placeholder=''"
                       onblur="this.placeholder='输入邮箱点击订阅吧(暂无)'"/>
                <i class="el-envelope"><input value=" " type="submit"/></i>
            </form>
            <i class="el-remove fx-close"></i>
        </div>

        <div class="bd-fx side-bdfx ">
            <i class="el-remove fx-close"></i>
            <ul class="bdsharebuttonbox">
                <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
            </ul>
            <script>window._bd_share_config = {
                "common": {
                    "bdSnsKey": {},
                    "bdText": "",
                    "bdMini": "2",
                    "bdMiniList": false,
                    "bdPic": "",
                    "bdStyle": "1",
                    "bdSize": "32"
                }, "share": {}
            };
            with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
        </div>
    </div>
    <!--最新更新-->

    <div class="clos-new bg-color animation-div">
        <h4 class="index-title"><i class="el-bulb"></i>最新资讯
            <small>Latest News</small>
        </h4>
        <ul>
            <li><i class="el-cloud"></i>
                <iframe id="tianqi" scrolling="no" frameborder="0" allowtransparency="true"
                        src="http://i.tianqi.com/index.php?c=code&a=getcode&id=34&h=25&w=280"></iframe>
            </li>

            <li><i class="el-calendar"></i>历史今天：
                <iframe src="http://www.todayonhistory.com/code/6.html?w=250&h=20&bky=dotted&bks=0&fs=14&fc=#565656&hg=14&ie=0&xhx=none&sd=300&px=3&len=0&sk=1&n=0"
                        width="250" height="15" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
            </li>
        </ul>
    </div>
    <!--搜索-->
    <div class="search animation-div">
        <form action="{% url "blog:search" %}" method="get">
            <div class="search-index">
                <input name="key" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                       onblur="this.placeholder='请输入关键字'"/>
                <i class="el-search"><input value=" " type="submit"/></i>
            </div>
        </form>
    </div>

    <!--文章排行tab-->
    <div class="mytab bg-color animation-div">
        <div class="tab-btn"><a class="hd-btn tab-active" href="javascript:;"><i class="el-comment-alt"></i>最新评论</a><a
                class="ph-btn" href="javascript:;"><i class="el-signal"></i>文章排行</a></div>
        <ul class="hudong-ul">
            <!--=======查询相册=============-->
            {% for comment in comment_list %}
                <li>
                    <div class="sd-name">
                        <span><i class="el-book"></i>{{ comment.title }}</span>
                        <a class="blue-text" href="{{ comment.url }}" title="{{ comment.comment }}">{{ comment.comment }}</a>
                        <span style="text-align: right">— &nbsp;<i class="el-user"></i>{{ comment.user }}</span>
                    </div>
                </li>
            {% endfor %}


        </ul>
        <!--文章排行-->
        <ul class="paihang-ul">
            {% for article in article_rank %}
                <li><span></span><a href="{% url "blog:detail" article.id %}"
                                    title="{{ article.title }}">{{ article.title }}<b><i
                        class="el-eye-open"></i>({{ article.read_nums }})</b></a></li>
            {% endfor %}
        </ul>

    </div>

    <!--标签-->
    <div class="cloud bg-color animation-div">
        <h4 class="index-title"><i class="el-tags"></i>标签云
            <small>Tags Clouds</small>
        </h4>
        <ul id="3dcloud">
            {% for tag in tag_list %}
                <li><a href="{% url "blog:tag" tag.id %}" title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a></li>
            {% endfor %}
        </ul>
    </div>


    <!--友情链接-->
    {% include "blogroll.html" %}
</aside>

templates/search.html
{% extends "base.html" %}

{% block title %}
    <title>搜索:{{ key }} - 烂笔头</title>
{% endblock %}

{% load custom_filter %}
{% block content %}
    {% paginate article_list 8 %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:article" pk=0 %}"><i class="el-search"></i> 搜索到<b class="lable">{{ key }}</b>相关结果</a>
            <span style="float:right;margin-right:10px;">共:<a class="orange-text"> {{ count }} </a>条</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.read_nums > 500 %}id="tuijian"{% elif article.read_nums > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ MEDIA_URL }}{{ article.image }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.edit_time }} 发表 "><i class="el-time"></i> {{ article.edit_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.conment_nums }} 条评论"><i class="el-comment"></i>{{ article.conment_nums }}</a>
                            </li>
                            <li><a title="已有 {{ article.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ article.read_nums }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "blog:article" article.category.id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category.name }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>

{% endblock %}